# Generated by Django 4.1.7 on 2023-03-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
